Traceback (most recent call last):
  File "C:\Users\sofmo\miniconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\sofmo\miniconda3\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sofmo\miniconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sofmo\miniconda3\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\sofmo\miniconda3\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\sofmo\miniconda3\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\sofmo\miniconda3\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Split "2025 Cook PVI" into Party and Number
house_pvi[['PVI_Party','PVI_Number']] = (
    house_pvi['2025 Cook PVI']
    .str.split('+', n=1, expand=True)
)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[2], line 3[0m
[0;32m      1[0m [38;5;66;03m# Split "2025 Cook PVI" into Party and Number[39;00m
[0;32m      2[0m house_pvi[[[38;5;124m'[39m[38;5;124mPVI_Party[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mPVI_Number[39m[38;5;124m'[39m]] [38;5;241m=[39m (
[1;32m----> 3[0m     [43mhouse_pvi[49m[[38;5;124m'[39m[38;5;124m2025 Cook PVI[39m[38;5;124m'[39m]
[0;32m      4[0m     [38;5;241m.[39mstr[38;5;241m.[39msplit([38;5;124m'[39m[38;5;124m+[39m[38;5;124m'[39m, n[38;5;241m=[39m[38;5;241m1[39m, expand[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[0;32m      5[0m )

[1;31mNameError[0m: name 'house_pvi' is not defined

